name: Deploy to Lolipop

on:
  push:
    branches:
      - main  # mainブランチに更新があった時に実行

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.lolipop.jp         # ★【重要】先ほどメモしたFTPSサーバー名に変更してください
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./it-hub/                 # ★【重要】ロリポップの公開先フォルダを指定します（よくわからなければ "/" のままで試してみてください）
